openapi: "3.0.0"
info:
  version: 1.0.0
  title: MT-WAN Config Worker
  license:
    name: MIT
servers:
  - url: http://localhost/v1
paths:
  /{hostname}/console:
    parameters:
    - $ref: "#/components/parameters/hostname"
  /{hostname}/console/[36m/console:
    parameters:
    - $ref: "#/components/parameters/hostname"
  /{hostname}/console/>:
    parameters:
    - $ref: "#/components/parameters/hostname"
  /{hostname}/console/test@[32mIrishaTik]:
    parameters:
    - $ref: "#/components/parameters/hostname"

components:
  parameters:
    hostname:
      in: path
      name: hostname
      required: true
      description: The management hostname/IP of the node
      schema:
        type: string
        example: r1.london.company.com
    fields:
      in: query
      name: fields
      schema:
        type: array
        items:
          type: string
    where:
      in: query
      name: where
      style: deepObject
      explode: true
      schema:
        type: object
    limit:
      in: query
      name: limit
      schema:
        type: number
    ids:
      in: query
      name: ids
      required: true
      schema:
        type: array
        items:
          type: string
          example: '*1'

  schemas:
    id:
      type: object
      properties:
        .id:
          type: string
          description: "Unique ID of the entity. NOT persistent across device reboots"
          example: "*1"
    read_only_obj:
      type: object
      additionalProperties:
        type: string
        readOnly: true
